language: python
python: 3.7
cache:
 directories:
  - $HOME/miniconda3


env:
  - TEST=tools/msPurity/purityA.xml
  - TEST=tools/msPurity/combineAnnotations.xml
  - TEST=tools/msPurity/spectralMatching.xml
  - TEST=tools/msPurity/dimsPredictPuritySingle.xml
  - TEST=tools/msPurity/filterFragSpectra.xml
  - TEST=tools/msPurity/createDatabase.xml
  - TEST=tools/msPurity/averageFragSpectra.xml
  - TEST=tools/msPurity/createMSP.xml
  - TEST=tools/msPurity/flagRemove.xml
  - TEST=tools/msPurity/frag4feature.xml
  - TEST=tools/msPurity/purityX.xml
  - TEST=tools/utils/msp_split/msp_split.xml
  - TEST=tools/utils/submit_to_mogi.xml


before_install:
 - pip install --upgrade pip setuptools
 - pip install planemo
 
 
script:
- planemo lint ${TRAVIS_BUILD_DIR}/${TEST} --galaxy_python_version 3.7
- planemo test  --conda_debug  ${TRAVIS_BUILD_DIR}/${TEST} --galaxy_python_version 3.7

